sudo: required
language: python
env:
  - DJ_TEST_HOST="127.0.0.1" DJ_TEST_USER="datajoint" DJ_TEST_PASSWORD="datajoint" DJ_HOST="127.0.0.1" DJ_USER="datajoint" DJ_PASS="datajoint"
python:
  - "3.4"
  - "3.5"
services: mysql
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-dev gfortran
  - mysql -e "create user 'datajoint'@'%' identified by 'datajoint'; GRANT ALL PRIVILEGES ON \`djtest\_%\`.* TO 'datajoint'@'%';" -uroot
install:
  - travis_wait 30 pip install -r requirements.txt
  - pip install nose nose-cov python-coveralls
# command to run tests
script:
  - nosetests -vv --with-coverage --cover-package=datajoint

after_success:
  - coveralls
