version: '2.1'
services:
  datajoint:
    build: .
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - DJ_TEST_HOST=db
      - DJ_TEST_USER="datajoint"
      - DJ_TEST_PASSWORD="datajoint"
      - S3_HOST=minio
      - S3_ACCESS_KEY="datajoint"
      - S3_SECRET_KEY="datajoint"
      - S3_BUCKET="datajoint-test"
    volumes:
      - .:/src
    links:
      - db
      - minio
    ports:
      - "8888:8888"
  db:
    image: datajoint/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=simple
    ports:
      - "3306:3306"
  minio:
    environment:
      - "MINIO_ACCESS_KEY=datajoint"
      - "MINIO_SECRET_KEY=datajoint"
    image: minio/minio
    ports:
      - "9000:9000"
    command: server /data
  createbuckets:
    environment:
      - "MINIO_ACCESS_KEY=datajoint"
      - "MINIO_SECRET_KEY=datajoint"
      - "MINIO_BUCKET=datajoint-test"
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "mc config host add dj-s3 http://minio:9000 $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY;mc mb $$MINIO_BUCKET;mc policy download $$MINIO_BUCKET;exit 0;"
